language: node_js
node_js:
- node
- '10'
before_install:
- openssl aes-256-cbc -K $encrypted_581bdbdcb727_key -iv $encrypted_581bdbdcb727_iv
  -in client-secret.json.enc -out client-secret.json -d
before_deploy:
  - yarn build
deploy:
  provider: gae
  keyfile: client-secret.json
  project: ruroutes-209901
