language: node_js
node_js:
  - node
addons:
  ssh_known_hosts: scarletbus.com
cache:
  yarn: true
  directories:
    - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_3ea5f71d02fc_key -iv $encrypted_3ea5f71d02fc_iv
  -in travis_rsa.enc -out travis_rsa -d
- chmod 600 travis_rsa
- mv travis_rsa ~/.ssh/id_rsa

script: yarn test

deploy:
  skip_cleanup: true
  provider: script
  script: .travis/deploy.sh
